Create secret social media platform
MkrtichSargsyan/Members-Only pull request #3
Opened 2020-11-19 02:17 UTC by MkrtichSargsyan

This project creates a secret social media platform where only authorized members can see who posted a ''crazy task''. This project was build as a result of inspiration by the novel of Chuck Palahniuk

2020-11-19 04:08 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @MkrtichSargsyan, 
Great job! 👏  I must say I am really impressed at the level you have taken this project to, super awesome. Let this good work continue. 👍  Excellent UI.

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review, I am quite sure it won't be a problem to address the necessary changes.

- [x] Update your readme file with a missing installation instruction, `yarn install`. I needed to run that before I could `rails db:migrate`

- [x] There should be absolutely **NO logic in views**.  Views are only for displaying information that became available to it from its corresponding controller not generating it.
View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)

**Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

This [article ](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)would come in handy 

Kindly address the request changes above as well as the comments I have made below on your code.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-19 04:08 UTC, acushlakoncept commented on config/routes.rb
> +  resources :users # , except: [:new]
Kindly update your application routes to use `resources :posts, only: [:new, :create, :index]` as this is one of the project requirements ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2020-11-19 04:08 UTC, acushlakoncept commented on app/views/layouts/_alerts.html.erb
> +<% end %>
There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.

2020-11-19 04:08 UTC, acushlakoncept commented on app/views/layouts/_navigation.html.erb
> +      <% end %>
There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.

2020-11-19 04:08 UTC, acushlakoncept commented on app/views/posts/_post.html.erb
> +              <% end %>
There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.

2020-11-19 04:08 UTC, acushlakoncept commented on app/views/users/index.html.erb
> +            <% end %>
There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it.

2020-11-19 04:08 UTC, acushlakoncept commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
Let's have a clean codebase, by removing unused/unnecessary comments. It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-11-19 04:08 UTC, acushlakoncept commented on app/views/pages/home.html.erb
> +      <%# <%= current_user.name %>
Let's have a clean codebase, by removing unused/unnecessary comments. It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-11-20 11:01 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2020-11-20 11:13 UTC, merged